### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by nitinprojects** [nitinprojects/wheel#6]

**Comment by nitinprojects** [comment]
Deployed at  [deployed-app-link](https://wheel-nitinprojects-production.herokuapp.com/)

Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink   please review.

**Comment by yedhink** [comment]
@nitinprojects I have provided some reviews. Once you address them and fix them, please lemme know over here.

**Comment by nitinprojects** [comment]
@yedhink I have made the change here #18. Please review!

**Comment by yedhink** [comment]
@nitinprojects I have added few more comments in the linked PR. Once you take care of them you can mark the neetoUI challenge as completed and then point out in the channel the same.

**Comment by nitinprojects** [comment]
@yedhink  I have made the requested changes here PR #19.
